# Generated by Django 3.0.6 on 2020-06-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='observed_cars',
            field=models.ManyToManyField(blank=True, to='products.Car'),
        ),
        migrations.AddField(
            model_name='account',
            name='observed_motorcycles',
            field=models.ManyToManyField(blank=True, to='products.Motorcycle'),
        ),
        migrations.AddField(
            model_name='account',
            name='observed_parts',
            field=models.ManyToManyField(blank=True, to='products.Part'),
        ),
    ]
