# Generated by Django 3.0.6 on 2020-07-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200627_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('small_car', 'Small car'), ('city_car', 'City car'), ('compact', 'Compact'), ('sedan', 'Sedan'), ('combi', 'Combi'), ('minivam', 'Minivam'), ('suv', 'SUV'), ('cabriolet', 'Cabriolet'), ('Coupe', 'Coupe')], default='city_car', max_length=9, verbose_name='Type of car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='num_of_doors',
            field=models.PositiveIntegerField(default=4, verbose_name='number of doors'),
            preserve_default=False,
        ),
    ]
