# Generated by Django 3.0.6 on 2020-07-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200702_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/cars/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='ImageMotorcycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/cars/%Y/%m/%d/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Motorcycle')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/cars/%Y/%m/%d/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Part')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('small_car', 'Small car'), ('city_car', 'City car'), ('compact', 'Compact'), ('sedan', 'Sedan'), ('combi', 'Combi'), ('minivan', 'Minivan'), ('suv', 'SUV'), ('cabriolet', 'Cabriolet'), ('Coupe', 'Coupe')], max_length=9, verbose_name='Type of car'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='imagecar',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Car'),
        ),
    ]
