# Generated by Django 3.0.6 on 2020-07-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200703_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecar',
            old_name='seller',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='imagemotorcycle',
            old_name='seller',
            new_name='motorcycle',
        ),
        migrations.RenameField(
            model_name='imagepart',
            old_name='seller',
            new_name='part',
        ),
    ]
