# Generated by Django 3.0.6 on 2020-08-14 21:43

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200703_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='country_of_origin',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_production',
            field=models.CharField(choices=[('1990', 1990), ('1991', 1991), ('1992', 1992), ('1993', 1993), ('1994', 1994), ('1995', 1995), ('1996', 1996), ('1997', 1997), ('1998', 1998), ('1999', 1999), ('2000', 2000), ('2001', 2001), ('2002', 2002), ('2003', 2003), ('2004', 2004), ('2005', 2005), ('2006', 2006), ('2007', 2007), ('2008', 2008), ('2009', 2009), ('2010', 2010), ('2011', 2011), ('2012', 2012), ('2013', 2013), ('2014', 2014), ('2015', 2015), ('2016', 2016), ('2017', 2017), ('2018', 2018), ('2019', 2019), ('2020', 2020)], max_length=4, verbose_name='Year production'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='country_of_origin',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='year_production',
            field=models.CharField(choices=[('1990', 1990), ('1991', 1991), ('1992', 1992), ('1993', 1993), ('1994', 1994), ('1995', 1995), ('1996', 1996), ('1997', 1997), ('1998', 1998), ('1999', 1999), ('2000', 2000), ('2001', 2001), ('2002', 2002), ('2003', 2003), ('2004', 2004), ('2005', 2005), ('2006', 2006), ('2007', 2007), ('2008', 2008), ('2009', 2009), ('2010', 2010), ('2011', 2011), ('2012', 2012), ('2013', 2013), ('2014', 2014), ('2015', 2015), ('2016', 2016), ('2017', 2017), ('2018', 2018), ('2019', 2019), ('2020', 2020)], max_length=4, verbose_name='Year production'),
        ),
    ]
