# Generated by Django 3.0.6 on 2020-09-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200824_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='phonenumber_viwes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='phonenumber_viwes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='part',
            name='phonenumber_viwes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='part',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
