# Generated by Django 3.0.6 on 2020-09-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200904_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='phonenumber_viwes',
            new_name='phonenumber_views',
        ),
        migrations.RenameField(
            model_name='motorcycle',
            old_name='phonenumber_viwes',
            new_name='phonenumber_views',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='phonenumber_viwes',
            new_name='phonenumber_views',
        ),
    ]
